#TSETMC_GOPHER Global Configuration

# system configuration
system:
  db-type: 'postgres'
  thread: 70

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[TSETMC_GOPHER]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: false


# mysql connect configuration
mysql:
  host: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'bource'
  username: 'root'
  password: 'A234@rrr'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false

# postgres connect configuration
postgres:
  host: '127.0.0.1'
  db-name: 'bource'
  username: 'admin'
  password: 'A234@rrr'
  log-mode: false

#tsetmc links
links:
  TSE_TICKER_EXPORT_DATA_ADDRESS: "http://tsetmc.com/tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i=%s"
  TSE_TICKER_ADDRESS: "http://tsetmc.com/Loader.aspx?ParTree=151311&i=%s"
  TSE_ISNT_INFO_URL: "http://www.tsetmc.com/tsev2/data/instinfodata.aspx?i=%s&c=56%20"
  TSE_CLIENT_TYPE_DATA_URL: "http://www.tsetmc.com/tsev2/data/clienttype.aspx?i=%s"
  TSE_SYMBOL_ID_URL: "http://www.tsetmc.com/tsev2/data/search.aspx?skey=%s"
  TSE_DAILY_PRICE_INFO: "http://www.tsetmc.com/tsev2/chart/data/IntraDayPrice.aspx?i=%s"
  TSE_CHART_IMAGE_URL: "http://www.tsetmc.com/tsev2/chart/img/Inst.aspx?i=%s"
  TSE_FILTER_ALL_DATA_NAME: "http://www.tsetmc.com/tsev2/data/MarketWatchInit.aspx?h=0&r=0"
